-- TABLES

--USE cecs323og11;


CREATE TABLE PERSON(
    PERSONID VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONENUMBER VARCHAR(12) NOT NULL,

    PRIMARY KEY(PERSONID)
);

CREATE TABLE SERVICEPACKAGE (
    packageCode INT NOT NULL,
    packageCost FLOAT NOT NULL,

    PRIMARY KEY(PACKAGECODE)
);


CREATE TABLE ZIP(
    ZIPNUMBER INT NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    stateCode VARCHAR(2) NOT NULL,

    PRIMARY KEY(ZIPNUMBER)
);

CREATE TABLE ADDRESS (
    ADDRESS VARCHAR (40) NOT NULL,
    ADDRESSTYPE VARCHAR (20) NOT NULL,
    ZIP INT NOT NULL,
    PERSONID VARCHAR(20) NOT NULL,

    PRIMARY KEY (ADDRESS, personid),
    FOREIGN KEY (PERSONID) REFERENCES PERSON (PERSONID),
    FOREIGN KEY (ZIP) REFERENCES ZIP(ZIPNUMBER)
);


CREATE TABLE CUSTOMER (
    CUSTOMERID VARCHAR(20) NOT NULL,
    CUSTOMERTYPE VARCHAR(20) NOT NULL,
    REFERREDBY VARCHAR(20) NOT NULL,
    CUSTOMERLEVEL VARCHAR(20) NOT NULL,
    TOTALSPENT INT NOT NULL,

    CHECK(CUSTOMERLEVEL IN('premier', 'steady', 'prospective')),

    PRIMARY KEY (CUSTOMERID),
    FOREIGN KEY (CUSTOMERID) REFERENCES PERSON (PERSONID)
    
);

CREATE TABLE STEADY(
    CUSTOMERID VARCHAR(20) NOT NULL,
    LOYALTYPOINTS VARCHAR(10) NOT NULL,
    ANNUALTOTAL FLOAT NOT NULL,
    
    PRIMARY KEY(CUSTOMERID),
    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);
CREATE TABLE PREMIER(
    CUSTOMERID VARCHAR(20) NOT NULL,
    MONTHLYFEE FLOAT NOT NULL,
    BONUS int NOT NULL,
    
    PRIMARY KEY(CUSTOMERID),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);
CREATE TABLE PROSPECTIVE(
    CUSTOMERID VARCHAR(20) NOT NULL,
    CONTACTATTEMPTS int NOT NULL,
    
    PRIMARY KEY(CUSTOMERID),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);


CREATE TABLE EMPLOYEE(
    EMPLOYEEID VARCHAR(20) NOT NULL,
    TITLE VARCHAR(15) NOT NULL,
    SALARY FLOAT NOT NULL,
    CHECK(TITLE IN('MECHANIC', 'SERVICETECH')),

    PRIMARY KEY(EMPLOYEEID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES PERSON(PERSONID)
);

CREATE TABLE MECHANIC(
    EMPLOYEEID VARCHAR(20) NOT NULL,

    PRIMARY KEY(EMPLOYEEID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);


CREATE TABLE SERVICETECH (
    EMPLOYEEID VARCHAR(20) NOT NULL,

    PRIMARY KEY(EMPLOYEEID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)


);

CREATE TABLE SKILL(
    TITLEOFSKILL VARCHAR(20) NOT NULL,
    PRIMARY KEY(TITLEOFSKILL)
);

CREATE TABLE MASTERYLEVEL(
    EMPLOYEEID VARCHAR(20) NOT NULL,
    TITLEOFSKILL VARCHAR(20) NOT NULL,
    mLevel INT NOT NULL,

    PRIMARY KEY(EMPLOYEEID, TITLEOFSKILL),
    FOREIGN KEY(EMPLOYEEID) REFERENCES MECHANIC(EMPLOYEEID),
    FOREIGN KEY(TITLEOFSKILL) REFERENCES SKILL(TITLEOFSKILL)
);


CREATE TABLE MENTORSHIP(
    MENTORID VARCHAR(20) NOT NULL,
    MENTEEID VARCHAR(20) NOT NULL,
    TITLEOFSKILL VARCHAR(20) NOT NULL,
    mStart DATE NOT NULL,
    mEnd DATE,

    PRIMARY KEY(MENTORID, MENTEEID, TITLEOFSKILL),
    FOREIGN KEY(MENTORID) REFERENCES MECHANIC(EMPLOYEEID),
    FOREIGN KEY(MENTEEID) REFERENCES MECHANIC(EMPLOYEEID),
    FOREIGN KEY(TITLEOFSKILL) REFERENCES SKILL(TITLEOFSKILL)
);

CREATE TABLE VIN(
    VIN VARCHAR(20) NOT NULL,
    make varchar(50) NOT NULL,
    model varchar(50) NOT NULL,
    vYear INT NOT NULL,

    PRIMARY KEY(VIN)
);


CREATE TABLE VEHICLE (
    customerID VARCHAR(20) NOT NULL,
    vin VARCHAR(20) NOT NULL,
    estimatedMileage INT NOT NULL,
    mileageInterval INT NOT NULL,
    accident BOOLEAN NOT NULL,

    PRIMARY KEY (vin, customerID),
    --FOREIGN KEY (vin) REFERENCES VIN(VIN),
    FOREIGN KEY (customerID) REFERENCES customer (customerID)
);

SHOW ENGINE INNODB STATUS;

CREATE TABLE SERVICEVISIT(
    CUSTOMERID VARCHAR(20) NOT NULL,
    EMPLOYEEID VARCHAR(20) NOT NULL,
    svDate DATE NOT NULL,
    svTime TIME NOT NULL,
    SERVICETYPE VARCHAR(20) NOT NULL,
    TOTALCOST FLOAT NOT NULL,
    PACKAGECODE INT,

    PRIMARY KEY(CUSTOMERID,EMPLOYEEID,svDate),

    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES SERVICETECH(EMPLOYEEID),
    FOREIGN KEY(PACKAGECODE) REFERENCES SERVICEPACKAGE(PACKAGECODE)
);

CREATE TABLE ServiceInterval (
    make varchar(50) NOT NULL,
    model varchar(50) NOT NULL,
    packageCode INT NOT NULL,
    mileage INT NOT NULL,

    PRIMARY KEY (make, model, packageCode, mileage),
    FOREIGN KEY (packageCode) REFERENCES SERVICEPACKAGE (packageCode)
);



CREATE TABLE SERVICEITEM (
    serviceCode INT NOT NULL,
    serviceName VARCHAR(25) NOT NULL,
    titleOfSkill VARCHAR(20) NOT NULL,
    timeDuration int NOT NULL,
    estimatedCost FLOAT NOT NULL,
    packageCode INT NOT NULL,
    PRIMARY KEY (serviceCode),
    FOREIGN KEY (titleOfSkill) REFERENCES SKILL (titleOfSkill),
    FOREIGN KEY (packageCode) REFERENCES SERVICEPACKAGE (packageCode)
);


CREATE TABLE SERVICEINSTANCE (
    CUSTOMERID VARCHAR(20) NOT NULL,
    SERVICETECHID VARCHAR(20) NOT NULL,
    siDate DATE NOT NULL,
    SERVICECODE INT NOT NULL,
    MECHANICID VARCHAR(20) NOT NULL,

    PRIMARY KEY(CUSTOMERID,SERVICETECHID,siDate,SERVICECODE),

    FOREIGN KEY(CUSTOMERID, SERVICETECHID, siDate) REFERENCES SERVICEVISIT(CUSTOMERID, EMPLOYEEID, svDate),
    FOREIGN KEY(SERVICECODE) REFERENCES SERVICEITEM (SERVICECODE),
    FOREIGN KEY(MECHANICID) REFERENCES MECHANIC(EMPLOYEEID)
);

CREATE TABLE APPOINTMENT (
    STEADYCUSTOMERID VARCHAR(20) NOT NULL,
    VIN VARCHAR(20) NOT NULL,
    aDate DATE NOT NULL, 
    aTime  TIME NOT NULL,
    
    PRIMARY KEY(STEADYCUSTOMERID, VIN),
    FOREIGN KEY(STEADYCUSTOMERID) REFERENCES STEADY(CUSTOMERID),
    FOREIGN KEY(VIN) REFERENCES VEHICLE(vin)
);