CREATE TABLE CUSTOMER (
    CUSTOMERID INT NOT NULL,
    CUSTOMERTYPE VARCHAR(20) NOT NULL,
    REFERREDBY VARCHAR(20) NOT NULL,
    CUSTOMERLEVEL VARCHAR(20) NOT NULL,
    TOTALSPENT INT NOT NULL,

    CHECK(CUSTOMERLEVEL IN('PREMIER', 'STEADY', 'PROSPECTIVE'))

    PRIMARY KEY (CUSTOMERID),
    FOREIGN KEY (CUSTOMERID) REFERENCES PERSON (PERSONID)
    
);



CREATE TABLE ADDRESS (
    ADDRESS VARCHAR (40) NOT NULL,
    ADDRESSTYPE VARCHAR (20) NOT NULL,
    ZIP INT (10) NOT NULL,
    PERSONID INT NOT NULL,

    PRIMARY KEY (ZIP),
    FOREIGN KEY (PERSONID) REFERENCES PERSON (PERSONID)
    




);


CREATE TABLE APPOINTMENT (

    
    CUSTOMERID INT NOT NULL,
    VIN VARCHAR(20) NOT NULL,
    "DATE" DATE NOT NULL, 
    "TIME"  TIME NOT NULL
    
    PRIMARY KEY(CUSTOMERID, VEHICLE),
    FOREIGN KEY(CUSTOMERID) REFERENCES STEADY (CUSTOMERID),
    FOREIGN KEY(VEHICLE) REFERENCES VEHICLE (VIN)

);


CREATE TABLE SERVICETECH (
    EMPLOYEEID INT NOT NULL,

    PRIMARY KEY(EMPLOYEEID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)


);

CREATE TABLE SERVICEVISIT(
    CUSTOMERID INT NOT NULL,
    EMPLOYEEID INT NOT NULL,
    "DATE" DATE NOT NULL,
    "TIME" TIME NOT NULL,
    SERVICETYPE VARCHAR(20) NOT NULL,
    TOTALCOST VARCHAR NOT NULL,
    PACKAGECODE INT NOT NULL,

    PRIMARY KEY(CUSTOMERID,EMPLOYEEID,"DATE"),

    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES SERVICETECH(EMPLOYEEID),
    FOREIGN KEY(PACKAGECODE) REFERENCES SERVICEPACKAGE(PACKAGECODE)

);



CREATE TABLE SERVICEINSTANCE (
    CUSTOMERID INT NOT NULL,
    SERVICETECHID VARCHAR(20) NOT NULL,
    "DATE" DATE NOT NULL,
    SERVICECODE INT NOT NULL,
    MECHANICID INT NOT NULL,

    PRIMARY KEY(CUSTOMERID,SERVICETECHID,"DATE",SERVICECODE,MECHANICID),

    FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY(SERVICETECHID) REFERENCES SERVICEVISIT(EMPLOYEEID),
    FOREIGN KEY("DATE") REFERENCES SERVICEVISIT("DATE"),
    FOREIGN KEY(SERVICECODE) REFERENCES SERVICEITEM (SERVICECODE),
    FOREIGN KEY(MECHANICID) REFERENCES MECHANIC(EMPLOYEEID)



);